default_slug = "zoe-samurai"
default_src = "puzzles/zoe-samurai.jpg"

[[puzzles]]
label = "Zoe Samurai"
slug = "zoe-samurai"
src = "puzzles/zoe-samurai.jpg"

[[puzzles]]
label = "Zoe Potter"
slug = "zoe-potter"
src = "puzzles/zoe-potter.jpg"

[[puzzles]]
label = "Raora by Noy"
slug = "raora-by-noy"
src = "puzzles/raora-by-noy.avif"
