[watch]
ignore = [
  ".wrangler",
  "target",
  "node_modules",
  "dist",
  "worker",
  "cli",
]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
  "scripts/minify_dist_assets.sh",
]
