[package]
name = "heddobureika-worker"
version = "0.1.0"
edition = "2021"
license = "CC-BY-NC-SA-4.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
heddobureika-core = { path = "../core" }
js-sys = "0.3"
rkyv = "0.8.14"
worker = "0.7.4"
